### ISSUE TITLE
'relation "users" does not exist' when adding UsersList test and route (Chapter 10)

### ISSUE THREAD

**Issue by NotThatRonnieColeman** [testdrivenio/testdriven-kubernetes-app#13]
I'm on Chapter 10 of the Microservices course https://testdriven.io/courses/microservices-with-docker-flask-and-react/part-one-restful-routes/

After adding the `UsersList` route (and, before it, it's test case) your guide claims all my tests should pass... however, the new test is _still_ erroring:
```
(venv) [user testdriven-app]$ docker-compose exec users python manage.py test
test_app_is_development (test_config.TestDevelopmentConfig) ... ok
test_app_is_production (test_config.TestProductionConfig) ... ok
test_app_is_testing (test_config.TestTestingConfig) ... ok
test_add_user (test_users.TestUserService)
Ensure a new user can be added to the database. ... ERROR
test_users (test_users.TestUserService)
Ensure the /ping route behaves correctly. ... ok

======================================================================
ERROR: test_add_user (test_users.TestUserService)
Ensure a new user can be added to the database.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "users" does not exist
LINE 1: INSERT INTO users (username, email, active, created_date) VA...
...
...
...
```
I'm moving on by just omitting that specific edge case (tbd if that will fly with the rest of the tutorial) but hoping to get some feedback. LMK if i can share anything to help investigate.

**Comment by NotThatRonnieColeman** [comment]
~Figured it out~ Didn't figure out the _why_, but i fixed it so that the test case succeeds... in my `services/users/project/tests/base.py`, i had my `BaseTestCase.setUp()` function declared as `def setup(self):`, and not `def setUp(self):` (notice the casing on the 'U').

I assume something specifically calls `setUp()` (as a framework convention) and since it didn't exist (`setup` did instead), `db.create_all()` was never invoked so psycopg assumed that no relations existed...? Although on retrospect, i do remember the users table getting created in the `users_dev` db...

Anywho, posting details in case anyone runs into the same thing.

edit: modified for clarity

**Comment by mjhea0** [comment]
Glad you got it worked out. Feel free to email me when you run into issues in the future.
