### ISSUE TITLE
When I add a new API route, Swagger does not update

### ISSUE THREAD

**Issue by daddydrac** [testdrivenio/testdriven-kubernetes-app#20]
When I add a new API route, Swagger does not update; the added resource seems not to register within the api perhaps as well but I am not sure.

**Comment by mjhea0** [comment]
That's expected. You have to update the swagger.josn file. 

https://github.com/testdrivenio/testdriven-app-2.5/blob/master/services/swagger/swagger.json

If you want something that auto updates, look at this app: https://gitlab.com/testdriven/flask-tdd-docker

**Comment by daddydrac** [comment]
Is there a cmd line script to update that I can run, or is literally manual?
