### ISSUE TITLE
On Part 2.5 Client Docker - Container Exiting

### ISSUE THREAD

**Issue by btotharye** [testdrivenio/testdriven-kubernetes-app#21]
Still trying to figure out what is up but when I got to part https://testdriven.io/courses/microservices-with-docker-flask-and-react/part-two-react-and-docker/ seems like the client container just exits with the below, not sure why yet.

```
> react-scripts start

ℹ ｢wds｣: Project is running at http://172.18.0.5/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /app/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...
```

**Comment by mjhea0** [comment]
Do not use the latest version of Create React App / React Scripts (3.4.1). 

https://github.com/facebook/create-react-app/issues/8688

**Comment by btotharye** [comment]
I’ll test but I got this even using your code that is the older version as well.

**Comment by btotharye** [comment]
I get the same error even with your code.  I'll download your version and verify but having the same issue on `2.1.8` of React Scripts

**Comment by mjhea0** [comment]
That's odd. Can you reach out via email? michael@testdriven.io

**Comment by btotharye** [comment]
it was an issue on my side, I forgot to clean up my node modules dir.  We are good now, sorry for the uneeded issue. :)
